# Generated by Django 4.2.16 on 2026-07-03 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('amenazas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscenarioRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=12)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('tef_o_analista', models.FloatField(blank=True, null=True)),
                ('tef_mp_analista', models.FloatField(blank=True, null=True)),
                ('tef_p_analista', models.FloatField(blank=True, null=True)),
                ('tef_pert_efectivo', models.FloatField(blank=True, null=True)),
                ('justificacion_tef', models.TextField(blank=True)),
                ('consulta_ia_tef', models.TextField(blank=True)),
                ('fuentes_tef', models.TextField(blank=True)),
                ('impacto_c', models.IntegerField(blank=True, null=True)),
                ('impacto_i', models.IntegerField(blank=True, null=True)),
                ('impacto_d', models.IntegerField(blank=True, null=True)),
                ('impacto_max', models.IntegerField(blank=True, null=True)),
                ('va', models.IntegerField(blank=True, null=True)),
                ('p_nivel', models.IntegerField(blank=True, null=True)),
                ('d', models.FloatField(blank=True, null=True)),
                ('frc', models.FloatField(blank=True, null=True)),
                ('ri', models.FloatField(blank=True, null=True)),
                ('rr', models.FloatField(blank=True, null=True)),
                ('rr_simple', models.IntegerField(blank=True, null=True)),
                ('ale_pert_usd', models.FloatField(blank=True, null=True)),
                ('ale_p50_usd', models.FloatField(blank=True, null=True)),
                ('ale_p90_usd', models.FloatField(blank=True, null=True)),
                ('ale_p95_usd', models.FloatField(blank=True, null=True)),
                ('prob_excedencia_200k', models.FloatField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, choices=[('critico', 'Crítico'), ('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=10)),
                ('estrategia_tratamiento', models.CharField(blank=True, choices=[('mitigar', 'Mitigar'), ('transferir', 'Transferir'), ('aceptar', 'Aceptar'), ('evitar', 'Evitar')], max_length=12)),
                ('sugerencia_ia_tratamiento', models.TextField(blank=True)),
                ('costo_control_estimado_usd', models.FloatField(blank=True, null=True)),
                ('roi_estimado', models.FloatField(blank=True, null=True)),
                ('decision_analista', models.TextField(blank=True)),
                ('aprobado_por', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('tef_pendiente', 'TEF pendiente'), ('calculado', 'Calculado'), ('evaluado', 'Evaluado'), ('en_tratamiento', 'En tratamiento'), ('completado', 'Completado')], default='borrador', max_length=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios', to='activos.activo')),
                ('amenaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escenarios', to='amenazas.amenaza')),
                ('control_existente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escenarios', to='amenazas.control')),
                ('controles_propuestos', models.ManyToManyField(blank=True, related_name='escenarios_propuestos', to='amenazas.control')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escenarios_creados', to=settings.AUTH_USER_MODEL)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios_riesgo', to='organizacion.organizacion')),
                ('vulnerabilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escenarios', to='amenazas.vulnerabilidad')),
            ],
            options={
                'verbose_name': 'Escenario de Riesgo (wizard)',
                'verbose_name_plural': 'Escenarios de Riesgo (wizard)',
                'ordering': ['-rr_simple', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='SimulacionMonteCarlo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_iteraciones', models.IntegerField(default=10000)),
                ('tef_o', models.FloatField()),
                ('tef_mp', models.FloatField()),
                ('tef_p', models.FloatField()),
                ('frc_usado', models.FloatField()),
                ('impacto_c', models.IntegerField(blank=True, null=True)),
                ('impacto_i', models.IntegerField(blank=True, null=True)),
                ('impacto_d', models.IntegerField(blank=True, null=True)),
                ('ale_media', models.FloatField()),
                ('ale_p50', models.FloatField()),
                ('ale_p90', models.FloatField()),
                ('ale_p95', models.FloatField()),
                ('prob_excedencia_200k', models.FloatField()),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones', to='riesgos.escenarioriesgo')),
            ],
            options={
                'ordering': ['-ejecutado_en'],
            },
        ),
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('activos', models.CharField(blank=True, max_length=120)),
                ('p', models.IntegerField(default=1, help_text='Probabilidad 1–5')),
                ('i', models.IntegerField(default=1, help_text='Impacto 1–5 = máx(C,I,D)')),
                ('d', models.FloatField(default=1.0, help_text='Degradación')),
                ('frc', models.FloatField(default=1.0, help_text='Factor de reducción del control')),
                ('freq_o', models.FloatField(default=0.1)),
                ('freq_mp', models.FloatField(default=1)),
                ('freq_p', models.FloatField(default=4)),
                ('ale_pert', models.FloatField(blank=True, null=True)),
                ('ale_p90', models.FloatField(blank=True, null=True)),
                ('rr', models.IntegerField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, max_length=20)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios', to='organizacion.organizacion')),
            ],
            options={
                'verbose_name': 'Escenario de Riesgo',
                'verbose_name_plural': 'Escenarios de Riesgo',
                'ordering': ['-rr', 'codigo'],
            },
        ),
    ]
