# Generated by Django 4.2.16 on 2026-07-03 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_magerit', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion_medisalud', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('natural', 'Natural'), ('accidental', 'Accidental'), ('no_intencional', 'No intencional'), ('intencional', 'Intencional')], default='intencional', max_length=20)),
                ('tef_o', models.FloatField(default=0)),
                ('tef_mp', models.FloatField(default=0)),
                ('tef_p', models.FloatField(default=0)),
                ('tef_pert', models.FloatField(blank=True, null=True)),
                ('nivel_probabilidad', models.IntegerField(blank=True, null=True)),
                ('afecta_c', models.BooleanField(default=False)),
                ('afecta_i', models.BooleanField(default=False)),
                ('afecta_d', models.BooleanField(default=False)),
                ('activos_tipicos', models.TextField(blank=True)),
                ('es_critica_lopdp', models.BooleanField(default=False)),
                ('precargada', models.BooleanField(default=True)),
                ('activos', models.ManyToManyField(blank=True, related_name='amenazas', to='activos.activo')),
            ],
            options={
                'verbose_name': 'Amenaza',
                'verbose_name_plural': 'Amenazas',
                'ordering': ['grupo__codigo', 'id_magerit'],
            },
        ),
        migrations.CreateModel(
            name='GrupoAmenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vuln', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion_medisalud', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('tecnologica', 'Tecnológica'), ('organizacional', 'Organizacional'), ('proceso', 'De proceso')], default='tecnologica', max_length=15)),
                ('severidad', models.IntegerField(choices=[(5, 'MA · Muy Alta'), (4, 'A · Alta'), (3, 'M · Media'), (2, 'B · Baja'), (1, 'MB · Muy Baja')], default=3)),
                ('degradacion', models.FloatField(blank=True, null=True)),
                ('afecta_c', models.BooleanField(default=False)),
                ('afecta_i', models.BooleanField(default=False)),
                ('afecta_d', models.BooleanField(default=False)),
                ('precargada', models.BooleanField(default=True)),
                ('amenazas_asociadas', models.ManyToManyField(blank=True, related_name='vulnerabilidades', to='amenazas.amenaza')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilidades', to='organizacion.organizacion')),
            ],
            options={
                'verbose_name': 'Vulnerabilidad',
                'verbose_name_plural': 'Vulnerabilidades',
                'ordering': ['id_vuln'],
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_control', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('referencia_iso', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('ausente', 'Ausente'), ('parcial', 'Parcial'), ('implementado', 'Implementado y auditado')], default='parcial', max_length=14)),
                ('frc', models.FloatField(blank=True, null=True)),
                ('activos_protegidos', models.TextField(blank=True)),
                ('precargado', models.BooleanField(default=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='organizacion.organizacion')),
                ('vulnerabilidades_mitigadas', models.ManyToManyField(blank=True, related_name='controles', to='amenazas.vulnerabilidad')),
            ],
            options={
                'verbose_name': 'Control',
                'verbose_name_plural': 'Controles',
                'ordering': ['id_control'],
            },
        ),
        migrations.AddField(
            model_name='amenaza',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amenazas', to='amenazas.grupoamenaza'),
        ),
        migrations.AddField(
            model_name='amenaza',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenazas', to='organizacion.organizacion'),
        ),
    ]
