# Generated by Django 4.2.16 on 2026-07-03 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Ecuador', max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('num_empleados', models.IntegerField(default=0)),
                ('num_usuarios_sistemas', models.IntegerField(default=0)),
                ('num_pacientes_registrados', models.IntegerField(blank=True, null=True)),
                ('centros_atencion', models.CharField(blank=True, max_length=200)),
                ('modalidad_operacion', models.CharField(blank=True, max_length=300)),
                ('responsable_evaluacion', models.CharField(max_length=200)),
                ('responsable_seguridad', models.CharField(max_length=200)),
                ('responsable_cumplimiento', models.CharField(max_length=200)),
                ('regulaciones_aplicables', models.TextField(blank=True)),
                ('fecha_levantamiento', models.DateField()),
                ('horizonte_evaluacion_meses', models.IntegerField(default=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='MarcoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma', models.CharField(max_length=120)),
                ('elemento_incorporado', models.TextField()),
                ('aplicacion', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcos', to='organizacion.organizacion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
