# Generated by Django 4.2.16 on 2026-07-03 03:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('ejemplos', models.TextField(blank=True)),
                ('formula', models.CharField(choices=[('VAG', 'Valor Activo General (6 dimensiones)'), ('VAD', 'Valor Activo Digital (8 dimensiones)')], default='VAG', max_length=3)),
                ('dimensiones_extra', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de Activo',
                'verbose_name_plural': 'Tipos de Activo',
            },
        ),
        migrations.CreateModel(
            name='ProcesoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel_importancia', models.CharField(choices=[('critico', 'Crítico'), ('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], default='medio', max_length=10)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='organizacion.organizacion')),
            ],
            options={
                'verbose_name': 'Proceso de Negocio',
                'verbose_name_plural': 'Procesos de Negocio',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('propietario', models.CharField(blank=True, max_length=200)),
                ('custodio_tecnico', models.CharField(blank=True, max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('en_revision', 'En revisión')], default='activo', max_length=12)),
                ('procesa_datos_salud', models.BooleanField(default=False, help_text='Datos de salud = categoría especial LOPDP Art. 5 → C=5 automático')),
                ('dim_confidencialidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dim_integridad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dim_disponibilidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dim_legal', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dim_operativo', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dim_economico', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dim_exposicion', models.IntegerField(blank=True, null=True)),
                ('dim_sensibilidad', models.IntegerField(blank=True, null=True)),
                ('vag_score', models.IntegerField(blank=True, null=True)),
                ('vad_score', models.IntegerField(blank=True, null=True)),
                ('va_normalizado', models.IntegerField(blank=True, null=True)),
                ('nivel_criticidad', models.CharField(blank=True, max_length=20)),
                ('clasificacion_nc', models.CharField(blank=True, max_length=10)),
                ('clasificacion', models.CharField(blank=True, max_length=6)),
                ('controles_minimos', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='organizacion.organizacion')),
                ('proceso_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='activos.procesonegocio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.tipoactivo')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['codigo'],
            },
        ),
    ]
