# Generated by Django 4.2.16 on 2026-07-03 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('formula', models.CharField(blank=True, max_length=255)),
                ('linea_base', models.CharField(blank=True, max_length=60)),
                ('meta', models.CharField(blank=True, max_length=60)),
                ('umbral_alerta', models.CharField(blank=True, max_length=255)),
                ('frecuencia', models.CharField(blank=True, max_length=40)),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='organizacion.organizacion')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CicloMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(max_length=20)),
                ('nivel_riesgo_aplicable', models.CharField(max_length=60)),
                ('actividades', models.TextField()),
                ('disparadores_reevaluacion', models.TextField()),
                ('responsable', models.CharField(max_length=150)),
                ('orden', models.IntegerField(default=0)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_monitoreo', to='organizacion.organizacion')),
            ],
            options={
                'verbose_name': 'Ciclo de Monitoreo',
                'verbose_name_plural': 'Ciclos de Monitoreo',
                'ordering': ['orden'],
            },
        ),
    ]
