# Generated by Django 4.2.16 on 2026-07-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
        ('riesgos', '0001_initial'),
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('completada', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_monitoreo', to='riesgos.escenarioriesgo')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_monitoreo', to='organizacion.organizacion')),
            ],
            options={
                'verbose_name': 'Tarea de Monitoreo',
                'verbose_name_plural': 'Tareas de Monitoreo',
                'ordering': ['escenario_id', 'orden', 'id'],
            },
        ),
    ]
