# Generated by Django 4.2.16 on 2026-07-03 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escenario_codigo', models.CharField(max_length=10)),
                ('escenario_nombre', models.CharField(max_length=200)),
                ('rr', models.IntegerField(default=0)),
                ('estrategia', models.CharField(choices=[('mitigar', 'Mitigar'), ('transferir', 'Transferir'), ('aceptar', 'Aceptar'), ('evitar', 'Evitar')], default='mitigar', max_length=20)),
                ('controles', models.CharField(blank=True, max_length=120)),
                ('medidas', models.TextField(blank=True)),
                ('ale_actual', models.FloatField(default=0)),
                ('ale_objetivo', models.FloatField(default=0)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='organizacion.organizacion')),
            ],
            options={
                'verbose_name': 'Plan de Tratamiento',
                'verbose_name_plural': 'Planes de Tratamiento',
                'ordering': ['escenario_codigo'],
            },
        ),
    ]
